# Generated by Django 4.2.7 on 2023-11-24 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0002_adminpost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminpost',
            name='admin',
        ),
    ]
