# Generated by Django 4.2.7 on 2023-11-27 07:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0003_remove_adminpost_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminpost',
            name='Total_likes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Likedetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.PositiveSmallIntegerField()),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.adminpost')),
            ],
        ),
    ]
