version: '3.8'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: 'python manage.py runserver 0.0.0.0:8002'
    ports:
      - 8002:8002
    volumes:
      - .:/app
    depends_on:
      - db
  mq:
    build:
      context: .
      dockerfile: Dockerfile
    command: 'python -u consumer.py'
    depends_on:
      - db
  db:
    image: postgres:16
    environment:
      - POSTGRES_USER=bibin
      - POSTGRES_PASSWORD=bibin
      - POSTGRES_DB=microuser
    ports:
      - "5432:5432"