services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8001
    volumes:
      - .:/app
    ports:
      - "8001:8001"
    environment:
      - DJANGO_SETTINGS_MODULE=adminside.settings
    depends_on:
      - db
  mq:
    build:
      context: .
      dockerfile: Dockerfile
    command: 'python -u consumer.py'
    depends_on:
      - db

  db:
    image: postgres:latest  
    environment:
      POSTGRES_DB: microadmin
      POSTGRES_USER: bibin
      POSTGRES_PASSWORD: bibin